# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jzc3akGCO325iO_kWlxawxh2YEnzwjUg
"""

# ============================================================
# CELL 1 — SETUP (run this every session)
# ============================================================
from google.colab import drive
drive.mount('/content/drive')

BASE = '/content/drive/MyDrive/MyDentalData'

import os, json, pickle
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from PIL import Image, ImageOps
import torchvision.transforms as T
import matplotlib.pyplot as plt
import pandas as pd

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# ============================================================
# CELL 2 — ONE-TIME SETUP: unzip dataset directly into Drive
# (Only run this once, ever. Skip after the first time —
#  the folder will already exist in your Drive.)
# ============================================================
if not os.path.exists(f'{BASE}/dental_data'):
    !unzip '{BASE}/Aariz.zip' -d '{BASE}/dental_data'
    print("Unzipped to Drive — will persist across sessions now.")
else:
    print("Already unzipped in Drive — skipping.")

# ============================================================
# CELL 3 — Load pixel_size lookup (fast, always safe to rerun)
# ============================================================
mapping_df = pd.read_csv(f'{BASE}/dental_data/Aariz/cephalogram_machine_mappings.csv')
pixel_size_lookup = dict(zip(mapping_df['cephalogram_id'], mapping_df['pixel_size']))
print(f"Loaded {len(pixel_size_lookup)} pixel-size mappings")

# ============================================================
# CELL 4 — Build (or load cached) samples list
# ============================================================
def build_samples(img_dir, ann_dir):
    img_files = os.listdir(img_dir)
    id_to_imgfile = {os.path.splitext(f)[0]: f for f in img_files}
    ann_files = [f for f in os.listdir(ann_dir) if f.endswith('.json')]
    result = []
    for ann_file in ann_files:
        ceph_id = os.path.splitext(ann_file)[0]
        if ceph_id not in id_to_imgfile:
            continue
        with open(os.path.join(ann_dir, ann_file), 'r') as f:
            data = json.load(f)
        coords = {}
        for lm in data['landmarks']:
            if lm['symbol'] in ('A', 'N', 'B'):
                coords[lm['symbol']] = (lm['value']['x'], lm['value']['y'])
        if len(coords) == 3:
            result.append((os.path.join(img_dir, id_to_imgfile[ceph_id]), coords))
    return result

samples_cache = f'{BASE}/samples_cache.pkl'

if os.path.exists(samples_cache):
    with open(samples_cache, 'rb') as f:
        train_samples, valid_samples = pickle.load(f)
    print("Loaded cached samples list.")
else:
    train_samples = build_samples(
        f'{BASE}/dental_data/Aariz/train/Cephalograms',
        f'{BASE}/dental_data/Aariz/train/Annotations/Cephalometric Landmarks/Senior Orthodontists'
    )
    valid_samples = build_samples(
        f'{BASE}/dental_data/Aariz/valid/Cephalograms',
        f'{BASE}/dental_data/Aariz/valid/Annotations/Cephalometric Landmarks/Senior Orthodontists'
    )
    with open(samples_cache, 'wb') as f:
        pickle.dump((train_samples, valid_samples), f)
    print("Built and cached samples list.")

print(f"Train samples: {len(train_samples)}")
print(f"Valid samples: {len(valid_samples)}")

# ============================================================
# CELL 5 — Dataset class (with square-padding fix)
# ============================================================
class CephDataset(Dataset):
    def __init__(self, samples, target_size=512):
        self.samples = samples
        self.target_size = target_size
        self.to_tensor = T.ToTensor()

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, coords = self.samples[idx]
        img = Image.open(img_path).convert('L')
        orig_w, orig_h = img.size

        square_size = max(orig_w, orig_h)
        pad_left = (square_size - orig_w) // 2
        pad_top = (square_size - orig_h) // 2
        pad_right = square_size - orig_w - pad_left
        pad_bottom = square_size - orig_h - pad_top

        img_padded = ImageOps.expand(img, border=(pad_left, pad_top, pad_right, pad_bottom), fill=0)
        img_resized = img_padded.resize((self.target_size, self.target_size))
        img_tensor = self.to_tensor(img_resized)

        scale = self.target_size / square_size

        landmarks = []
        for symbol in ('A', 'N', 'B'):
            x, y = coords[symbol]
            new_x = (x + pad_left) * scale
            new_y = (y + pad_top) * scale
            landmarks.append(new_x)
            landmarks.append(new_y)

        return img_tensor, torch.tensor(landmarks, dtype=torch.float32)

train_dataset = CephDataset(train_samples, target_size=512)
valid_dataset = CephDataset(valid_samples, target_size=512)
train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
valid_loader = DataLoader(valid_dataset, batch_size=8, shuffle=False)

class CephNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 16, 3, padding=1)
        self.conv2 = nn.Conv2d(16, 32, 3, padding=1)
        self.conv3 = nn.Conv2d(32, 64, 3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)
        # Corrected input features for fc1 based on 512x512 input images
        # After 3 conv layers and 3 pooling layers (each halving size), a 512x512 image becomes 64x64
        self.fc1 = nn.Linear(64 * 64 * 64, 128)
        self.fc2 = nn.Linear(128, 6)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = self.pool(F.relu(self.conv3(x)))
        x = x.view(x.size(0), -1)
        x = F.relu(self.fc1(x))
        return self.fc2(x)

# ============================================================
# CELL 7 — Load existing trained model IF you have one saved,
# otherwise train fresh. Run this once per day, not per session-restart.
# ============================================================
model_path = f'{BASE}/cephnet_stage1.pth'

# If an incompatible saved model exists (due to architecture changes),
# delete it to force retraining with the new architecture.
if os.path.exists(model_path):
    print(f"Checking for saved model at: {model_path}")
    # Instantiate a temporary model to check for compatibility without loading weights
    temp_model = CephNet()
    try:
        # Attempt to load just to check if it's compatible. This will fail if not.
        torch.load(model_path)
        # If it reaches here, it means the file is loadable, but we still need to check architecture
        # For simplicity, given the explicit error about shape mismatch, we assume it's incompatible
        # and force retraining if the architecture doesn't match the current class definition.
        # A more robust check would involve comparing state_dict keys or shapes.
        # However, the previous error already established incompatibility.
        print("Existing model file found. Checking architecture compatibility.")
        # If the CephNet class has been modified in memory, the old saved model is likely incompatible.
        # The most straightforward way to proceed after an architecture change is to retrain.
        print("Detected architecture change or incompatibility. Deleting old model to force retraining.")
        os.remove(model_path)
        print("Old incompatible model deleted.")
    except Exception as e:
        print(f"Error attempting to inspect saved model (likely incompatible): {e}")
        print("Deleting old model to force retraining.")
        os.remove(model_path)
        print("Old incompatible model deleted.")

model = CephNet().to(device)

if os.path.exists(model_path):
    # This block will now only execute if the model_path was NOT deleted above,
    # which means it's a new session and a compatible model was somehow already there.
    model.load_state_dict(torch.load(model_path))
    print("Loaded existing trained model — no need to retrain.")
else:
    print("No saved model found or incompatible model deleted — will train from scratch below.")

# ============================================================
# CELL 8 — TRAINING (only run if you loaded no model above,
# or want to retrain / continue improving)
# ============================================================
optimizer = optim.Adam(model.parameters(), lr=0.001)
criterion = nn.MSELoss()

num_epochs = 30
train_losses, val_losses = [], []
best_val_loss = float('inf')

for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0
    for images, landmarks in train_loader:
        images, landmarks = images.to(device), landmarks.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, landmarks)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    train_loss = running_loss / len(train_loader)

    model.eval()
    val_running_loss = 0.0
    with torch.no_grad():
        for images, landmarks in valid_loader:
            images, landmarks = images.to(device), landmarks.to(device)
            outputs = model(images)
            loss = criterion(outputs, landmarks)
            val_running_loss += loss.item()
    val_loss = val_running_loss / len(valid_loader)

    train_losses.append(train_loss)
    val_losses.append(val_loss)
    print(f"Epoch {epoch+1}/{num_epochs} | Train MSE: {train_loss:.1f} | Val MSE: {val_loss:.1f}")

    # Save the BEST checkpoint, not just the last one (fixes the epoch-27-vs-30 issue noted earlier)
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), model_path)

print(f"\nBest val MSE: {best_val_loss:.1f} — saved to {model_path}")

# Reload the best checkpoint for evaluation below
model.load_state_dict(torch.load(model_path))

# ============================================================
# CELL 9 — EVALUATION: pixel MRE + correct per-image mm conversion
# ============================================================
model.eval()
landmark_names = ['A', 'N', 'B']
px_errors = {name: [] for name in landmark_names}
mm_errors = {name: [] for name in landmark_names}

with torch.no_grad():
    for i, (img_path, coords) in enumerate(valid_samples):
        ceph_id = os.path.splitext(os.path.basename(img_path))[0]
        if ceph_id not in pixel_size_lookup:
            continue
        pixel_size = pixel_size_lookup[ceph_id]

        img = Image.open(img_path).convert('L')
        orig_w, orig_h = img.size
        square_size = max(orig_w, orig_h)
        scale = 512 / square_size

        img_tensor, true_landmarks = valid_dataset[i]
        img_tensor = img_tensor.unsqueeze(0).to(device)
        pred = model(img_tensor).cpu().squeeze().numpy()
        true_np = true_landmarks.numpy()

        for j, name in enumerate(landmark_names):
            px_, py_ = pred[j*2], pred[j*2+1]
            tx, ty = true_np[j*2], true_np[j*2+1]
            dist_512 = ((px_-tx)**2 + (py_-ty)**2) ** 0.5
            dist_orig_px = dist_512 / scale
            dist_mm = dist_orig_px * pixel_size

            px_errors[name].append(dist_512)
            mm_errors[name].append(dist_mm)

print("--- Pixel error (512x512 space) ---")
for name in landmark_names:
    e = px_errors[name]
    print(f"{name}: mean={sum(e)/len(e):.2f} px, max={max(e):.2f} px, min={min(e):.2f} px")

print("\n--- Real-world error (mm) ---")
for name in landmark_names:
    e = mm_errors[name]
    print(f"{name}: mean={sum(e)/len(e):.3f} mm, max={max(e):.3f} mm, min={min(e):.3f} mm")

# ============================================================
# CELL 10 — Find and visualize the worst-error cases
# ============================================================
model.eval()
all_results = []  # (ceph_id, img_path, avg_error_mm, pred, true, orig_w, orig_h, square_size)

with torch.no_grad():
    for i, (img_path, coords) in enumerate(valid_samples):
        ceph_id = os.path.splitext(os.path.basename(img_path))[0]
        if ceph_id not in pixel_size_lookup:
            continue
        pixel_size = pixel_size_lookup[ceph_id]

        img = Image.open(img_path).convert('L')
        orig_w, orig_h = img.size
        square_size = max(orig_w, orig_h)
        scale = 512 / square_size

        img_tensor, true_landmarks = valid_dataset[i]
        img_tensor_batched = img_tensor.unsqueeze(0).to(device)
        pred = model(img_tensor_batched).cpu().squeeze().numpy()
        true_np = true_landmarks.numpy()

        errors_mm = []
        for j in range(3):
            px_, py_ = pred[j*2], pred[j*2+1]
            tx, ty = true_np[j*2], true_np[j*2+1]
            dist_512 = ((px_-tx)**2 + (py_-ty)**2) ** 0.5
            dist_mm = (dist_512 / scale) * pixel_size
            errors_mm.append(dist_mm)

        avg_error = sum(errors_mm) / 3
        all_results.append((ceph_id, img_path, avg_error, pred, true_np, img_tensor))

# Sort by worst average error, descending
all_results.sort(key=lambda x: x[2], reverse=True)

print("Worst 5 cases (by average mm error across A, N, B):")
for r in all_results[:5]:
    print(f"  {r[0]}: avg error = {r[2]:.2f} mm")

# ============================================================
# CELL 11 — Plot the worst 3 cases: predicted (red) vs true (green)
# ============================================================
landmark_names = ['A', 'N', 'B']

fig, axes = plt.subplots(1, 3, figsize=(15, 6))

for idx, (ceph_id, img_path, avg_err, pred, true_np, img_tensor) in enumerate(all_results[:3]):
    img_np = img_tensor.squeeze().numpy()
    axes[idx].imshow(img_np, cmap='gray')

    for j, name in enumerate(landmark_names):
        px_pred, py_pred = pred[j*2], pred[j*2+1]
        px_true, py_true = true_np[j*2], true_np[j*2+1]

        axes[idx].scatter(px_true, py_true, c='lime', s=10, marker='o', label='True' if j==0 else "")
        axes[idx].scatter(px_pred, py_pred, c='red', s=30, marker='x', label='Predicted' if j==0 else "")
        axes[idx].text(px_true+5, py_true, name, color='lime', fontsize=10)

    axes[idx].set_title(f"{ceph_id}\navg err: {avg_err:.1f}mm")
    axes[idx].legend(fontsize=8)

plt.tight_layout()
plt.show()

# Find this specific case in all_results (from the 512px evaluation run)
target_id = 'cl5lg05uc016u074k52t95p5v'

outlier_case = None
for r in all_results:
    if r[0] == target_id:
        outlier_case = r
        break

if outlier_case is None:
    print("Not found in current all_results — may need to rerun Cell 10 at 512px to regenerate it")
else:
    ceph_id, img_path, avg_err, pred, true_np, img_tensor = outlier_case

    img_np = img_tensor.squeeze().numpy()
    plt.figure(figsize=(7, 8))
    plt.imshow(img_np, cmap='gray')

    landmark_names = ['A', 'N', 'B']
    for j, name in enumerate(landmark_names):
        px_pred, py_pred = pred[j*2], pred[j*2+1]
        px_true, py_true = true_np[j*2], true_np[j*2+1]
        dist = ((px_pred-px_true)**2 + (py_pred-py_true)**2) ** 0.5

        plt.scatter(px_true, py_true, c='lime', s=20, marker='o')
        plt.scatter(px_pred, py_pred, c='red', s=20, marker='x')
        plt.text(px_true+8, py_true, f"{name} (err: {dist:.1f}px)", color='lime', fontsize=10)

    plt.title(f"{ceph_id}\navg error: {avg_err:.2f}mm — persistent worst case")
    plt.show()

for ceph_id in ['cl5lg05uc016u074k52t95p5v', 'cl5lg05ug01am074k5dbu39k7', 'cl5lg05ug01b6074k86t0bfw2']:
    print(f"{ceph_id}: pixel_size = {pixel_size_lookup.get(ceph_id, 'not found')}")

for ceph_id, img_path, avg_err, pred, true_np, img_tensor in all_results[:3]:
    px_dists = []
    for j in range(3):
        px_, py_ = pred[j*2], pred[j*2+1]
        tx, ty = true_np[j*2], true_np[j*2+1]
        px_dists.append(((px_-tx)**2 + (py_-ty)**2) ** 0.5)
    print(f"{ceph_id}: pixel-space errors = {[f'{d:.1f}' for d in px_dists]} px (512x512 space)")

import numpy as np

pixel_sizes = []
avg_errors_mm = []

for ceph_id, img_path, avg_err, pred, true_np, img_tensor in all_results:
    ps = pixel_size_lookup.get(ceph_id)
    if ps is not None:
        pixel_sizes.append(ps)
        avg_errors_mm.append(avg_err)

correlation = np.corrcoef(pixel_sizes, avg_errors_mm)[0, 1]
print(f"Correlation between pixel_size and mm error: {correlation:.3f}")

plt.scatter(pixel_sizes, avg_errors_mm, alpha=0.5)
plt.xlabel("pixel_size (mm/pixel)")
plt.ylabel("Average landmark error (mm)")
plt.title("Error vs. image resolution across all validation samples")
plt.show()